

SET NAMES utf8mb4;

INSERT INTO word_bank (id, word, category, scenario_id, active) VALUES
(UUID(), 'O sistema deve', 'prefixo', 1, 1),
(UUID(), 'O sistema deve', 'prefixo', 1, 1),
(UUID(), 'O sistema deve', 'prefixo', 1, 1),
(UUID(), 'O sistema deve', 'prefixo', 1, 1),
(UUID(), 'O sistema deve', 'prefixo', 1, 1),
(UUID(), 'O sistema deve', 'prefixo', 1, 1),
(UUID(), 'O sistema deve', 'prefixo', 1, 1),
(UUID(), 'O sistema deve', 'prefixo', 1, 1),
(UUID(), 'O sistema deve', 'prefixo', 1, 1),
(UUID(), 'O sistema deve', 'prefixo', 1, 1),
(UUID(), 'O sistema deve', 'prefixo', 1, 1),
(UUID(), 'O sistema deve', 'prefixo', 1, 1),
(UUID(), 'O sistema deve', 'prefixo', 1, 1),
(UUID(), 'O sistema deve', 'prefixo', 1, 1),
(UUID(), 'O sistema deve', 'prefixo', 1, 1),
(UUID(), 'O sistema deve', 'prefixo', 1, 1),
(UUID(), 'O sistema deve', 'prefixo', 1, 1),
(UUID(), 'O sistema deve', 'prefixo', 1, 1),
(UUID(), 'O sistema deve', 'prefixo', 1, 1),
(UUID(), 'O sistema deve', 'prefixo', 1, 1),
(UUID(), 'O sistema não pode', 'prefixo', 1, 1),
(UUID(), 'O sistema não pode', 'prefixo', 1, 1),
(UUID(), 'O sistema não pode', 'prefixo', 1, 1),
(UUID(), 'O sistema não pode', 'prefixo', 1, 1),
(UUID(), 'O sistema não pode', 'prefixo', 1, 1),
(UUID(), 'O sistema não pode', 'prefixo', 1, 1),
(UUID(), 'O sistema não pode', 'prefixo', 1, 1),
(UUID(), 'O sistema não pode', 'prefixo', 1, 1),
(UUID(), 'O sistema não pode', 'prefixo', 1, 1),
(UUID(), 'O sistema não pode', 'prefixo', 1, 1),
(UUID(), 'permitir', 'verbo', 1, 1),
(UUID(), 'permitir', 'verbo', 1, 1),
(UUID(), 'permitir', 'verbo', 1, 1),
(UUID(), 'permitir', 'verbo', 1, 1),
(UUID(), 'permitir', 'verbo', 1, 1),
(UUID(), 'permitir', 'verbo', 1, 1),
(UUID(), 'permitir', 'verbo', 1, 1),
(UUID(), 'permitir', 'verbo', 1, 1),
(UUID(), 'permitir', 'verbo', 1, 1),
(UUID(), 'permitir', 'verbo', 1, 1),
(UUID(), 'permitir', 'verbo', 1, 1),
(UUID(), 'permitir', 'verbo', 1, 1),
(UUID(), 'enviar', 'verbo', 1, 1),
(UUID(), 'enviar', 'verbo', 1, 1),
(UUID(), 'enviar', 'verbo', 1, 1),
(UUID(), 'enviar', 'verbo', 1, 1),
(UUID(), 'enviar', 'verbo', 1, 1),
(UUID(), 'enviar', 'verbo', 1, 1),
(UUID(), 'enviar', 'verbo', 1, 1),
(UUID(), 'enviar', 'verbo', 1, 1),
(UUID(), 'exibir', 'verbo', 1, 1),
(UUID(), 'exibir', 'verbo', 1, 1),
(UUID(), 'exibir', 'verbo', 1, 1),
(UUID(), 'exibir', 'verbo', 1, 1),
(UUID(), 'exibir', 'verbo', 1, 1),
(UUID(), 'disponibilizar', 'verbo', 1, 1),
(UUID(), 'disponibilizar', 'verbo', 1, 1),
(UUID(), 'disponibilizar', 'verbo', 1, 1),
(UUID(), 'disponibilizar', 'verbo', 1, 1),
(UUID(), 'disponibilizar', 'verbo', 1, 1),
(UUID(), 'disponibilizar', 'verbo', 1, 1),
(UUID(), 'realizar', 'verbo', 1, 1),
(UUID(), 'realizar', 'verbo', 1, 1),
(UUID(), 'realizar', 'verbo', 1, 1),
(UUID(), 'realizar', 'verbo', 1, 1),
(UUID(), 'manter', 'verbo', 1, 1),
(UUID(), 'manter', 'verbo', 1, 1),
(UUID(), 'manter', 'verbo', 1, 1),
(UUID(), 'autorizar', 'verbo', 1, 1),
(UUID(), 'autorizar', 'verbo', 1, 1),
(UUID(), 'autorizar', 'verbo', 1, 1),
(UUID(), 'postar', 'verbo', 1, 1),
(UUID(), 'postar', 'verbo', 1, 1),
(UUID(), 'criar', 'verbo', 1, 1),
(UUID(), 'criar', 'verbo', 1, 1),
(UUID(), 'criar', 'verbo', 1, 1),
(UUID(), 'funcionar', 'verbo', 1, 1),
(UUID(), 'funcionar', 'verbo', 1, 1),
(UUID(), 'funcionar', 'verbo', 1, 1),
(UUID(), 'funcionar', 'verbo', 1, 1),
(UUID(), 'receber', 'verbo', 1, 1),
(UUID(), 'receber', 'verbo', 1, 1),
(UUID(), 'receber', 'verbo', 1, 1),
(UUID(), 'perder', 'verbo', 1, 1),
(UUID(), 'perder', 'verbo', 1, 1),
(UUID(), 'tirar', 'verbo', 1, 1),
(UUID(), 'tirar', 'verbo', 1, 1),
(UUID(), 'fazer', 'verbo', 1, 1),
(UUID(), 'fazer', 'verbo', 1, 1),
(UUID(), 'fazer', 'verbo', 1, 1),
(UUID(), 'ser desenvolvido', 'verbo', 1, 1),
(UUID(), 'ser desenvolvido', 'verbo', 1, 1),
(UUID(), 'acionar', 'verbo', 1, 1),
(UUID(), 'acionar', 'verbo', 1, 1),
(UUID(), 'deslizar', 'verbo', 1, 1),
(UUID(), 'deslizar', 'verbo', 1, 1),
(UUID(), 'apresentar', 'verbo', 1, 1),
(UUID(), 'apresentar', 'verbo', 1, 1),
(UUID(), 'visualizar', 'verbo', 1, 1),
(UUID(), 'visualizar', 'verbo', 1, 1),
(UUID(), 'visualizar', 'verbo', 1, 1),
(UUID(), 'clicar', 'verbo', 1, 1),
(UUID(), 'clicar', 'verbo', 1, 1),
(UUID(), 'confirmar', 'verbo', 1, 1),
(UUID(), 'confirmar', 'verbo', 1, 1),
(UUID(), 'mensagens', 'objeto', 1, 1),
(UUID(), 'mensagens', 'objeto', 1, 1),
(UUID(), 'mensagens', 'objeto', 1, 1),
(UUID(), 'mensagens', 'objeto', 1, 1),
(UUID(), 'mensagens', 'objeto', 1, 1),
(UUID(), 'mensagens', 'objeto', 1, 1),
(UUID(), 'mensagens', 'objeto', 1, 1),
(UUID(), 'mensagens', 'objeto', 1, 1),
(UUID(), 'mensagens', 'objeto', 1, 1),
(UUID(), 'mensagens', 'objeto', 1, 1),
(UUID(), 'mensagens de voz', 'objeto', 1, 1),
(UUID(), 'mensagens de voz', 'objeto', 1, 1),
(UUID(), 'mensagens de voz', 'objeto', 1, 1),
(UUID(), 'mensagens de texto', 'objeto', 1, 1),
(UUID(), 'mensagens de texto', 'objeto', 1, 1),
(UUID(), 'mensagens de texto', 'objeto', 1, 1),
(UUID(), 'mensagens anônimas', 'objeto', 1, 1),
(UUID(), 'mensagens anônimas', 'objeto', 1, 1),
(UUID(), 'ligações por áudio', 'objeto', 1, 1),
(UUID(), 'ligações por áudio', 'objeto', 1, 1),
(UUID(), 'ligações por áudio', 'objeto', 1, 1),
(UUID(), 'ligações por vídeo', 'objeto', 1, 1),
(UUID(), 'ligações por vídeo', 'objeto', 1, 1),
(UUID(), 'ligações por vídeo', 'objeto', 1, 1),
(UUID(), 'chamada de telefone convencional', 'objeto', 1, 1),
(UUID(), 'chamada de telefone convencional', 'objeto', 1, 1),
(UUID(), 'print de imagens íntimas', 'objeto', 1, 1),
(UUID(), 'print de imagens íntimas', 'objeto', 1, 1),
(UUID(), 'fotos nos stories', 'objeto', 1, 1),
(UUID(), 'fotos nos stories', 'objeto', 1, 1),
(UUID(), 'fotos tiradas com a câmera do celular', 'objeto', 1, 1),
(UUID(), 'fotos tiradas com a câmera do celular', 'objeto', 1, 1),
(UUID(), 'arquivos nos formatos PDF, JPG, PNG, Excel e Word', 'objeto', 1, 1),
(UUID(), 'arquivos nos formatos PDF, JPG, PNG, Excel e Word', 'objeto', 1, 1),
(UUID(), 'grupos de usuários', 'objeto', 1, 1),
(UUID(), 'grupos de usuários', 'objeto', 1, 1),
(UUID(), 'um chatbot', 'objeto', 1, 1),
(UUID(), 'um chatbot', 'objeto', 1, 1),
(UUID(), 'um chatbot', 'objeto', 1, 1),
(UUID(), 'um meio de pagamento', 'objeto', 1, 1),
(UUID(), 'um meio de pagamento', 'objeto', 1, 1),
(UUID(), 'emojis', 'objeto', 1, 1),
(UUID(), 'emojis', 'objeto', 1, 1),
(UUID(), 'figurinhas', 'objeto', 1, 1),
(UUID(), 'figurinhas', 'objeto', 1, 1),
(UUID(), 'o histórico completo das mensagens', 'objeto', 1, 1),
(UUID(), 'o histórico completo das mensagens', 'objeto', 1, 1),
(UUID(), 'o status online', 'objeto', 1, 1),
(UUID(), 'o status online', 'objeto', 1, 1),
(UUID(), 'o ícone', 'objeto', 1, 1),
(UUID(), 'o ícone', 'objeto', 1, 1),
(UUID(), 'a tela de conversa', 'objeto', 1, 1),
(UUID(), 'a tela de conversa', 'objeto', 1, 1),
(UUID(), 'que o Interlocutor', 'complemento', 1, 1),
(UUID(), 'que o Interlocutor', 'complemento', 1, 1),
(UUID(), 'que o Interlocutor', 'complemento', 1, 1),
(UUID(), 'que o Interlocutor', 'complemento', 1, 1),
(UUID(), 'que o Interlocutor', 'complemento', 1, 1),
(UUID(), 'que o Interlocutor', 'complemento', 1, 1),
(UUID(), 'ao Interlocutor', 'complemento', 1, 1),
(UUID(), 'ao Interlocutor', 'complemento', 1, 1),
(UUID(), 'ao Interlocutor', 'complemento', 1, 1),
(UUID(), 'ao Interlocutor', 'complemento', 1, 1),
(UUID(), 'ao Interlocutor', 'complemento', 1, 1),
(UUID(), 'do Interlocutor', 'complemento', 1, 1),
(UUID(), 'do Interlocutor', 'complemento', 1, 1),
(UUID(), 'do Interlocutor', 'complemento', 1, 1),
(UUID(), 'do Interlocutor', 'complemento', 1, 1),
(UUID(), 'o modo anônimo', 'complemento', 1, 1),
(UUID(), 'o modo anônimo', 'complemento', 1, 1),
(UUID(), 'o status de', 'complemento', 1, 1),
(UUID(), 'o status de', 'complemento', 1, 1),
(UUID(), 'as mensagens enviadas', 'complemento', 1, 1),
(UUID(), 'as mensagens enviadas', 'complemento', 1, 1),
(UUID(), 'de uma única vez', 'complemento', 1, 1),
(UUID(), 'de uma única vez', 'complemento', 1, 1),
(UUID(), 'a vários interlocutores', 'complemento', 1, 1),
(UUID(), 'a vários interlocutores', 'complemento', 1, 1),
(UUID(), 'com base nas ações do interlocutor', 'complemento', 1, 1),
(UUID(), 'com base nas ações do interlocutor', 'complemento', 1, 1),
(UUID(), 'na conversa', 'complemento', 1, 1),
(UUID(), 'na conversa', 'complemento', 1, 1),
(UUID(), 'utilizando Blockchain completo', 'complemento', 1, 1),
(UUID(), 'utilizando Blockchain completo', 'complemento', 1, 1),
(UUID(), 'com criptografia utilizando o Signal Protocol', 'complemento', 1, 1),
(UUID(), 'com criptografia utilizando o Signal Protocol', 'complemento', 1, 1),
(UUID(), 'utilizando linguagem de programação Python', 'complemento', 1, 1),
(UUID(), 'utilizando linguagem de programação Python', 'complemento', 1, 1),
(UUID(), 'em plataformas com sistema operacional iOS e Android', 'complemento', 1, 1),
(UUID(), 'em plataformas com sistema operacional iOS e Android', 'complemento', 1, 1),
(UUID(), 'em no máximo 1 milissegundo', 'metrica', 1, 1),
(UUID(), 'em no máximo 1 milissegundo', 'metrica', 1, 1),
(UUID(), 'em até 10 milissegundos', 'metrica', 1, 1),
(UUID(), 'em até 10 milissegundos', 'metrica', 1, 1),
(UUID(), 'em até 3 segundos', 'metrica', 1, 1),
(UUID(), 'em até 3 segundos', 'metrica', 1, 1),
(UUID(), 'em um longo período', 'metrica', 1, 1),
(UUID(), 'em um longo período', 'metrica', 1, 1),
(UUID(), 'quando o Interlocutor estiver online', 'condicao', 1, 1),
(UUID(), 'quando o Interlocutor estiver online', 'condicao', 1, 1),
(UUID(), 'quando ele ativar', 'condicao', 1, 1),
(UUID(), 'quando ele ativar', 'condicao', 1, 1),
(UUID(), 'quando ele sair', 'condicao', 1, 1),
(UUID(), 'quando ele sair', 'condicao', 1, 1),
(UUID(), 'quando o Interlocutor clicar no ícone', 'condicao', 1, 1),
(UUID(), 'quando o Interlocutor clicar no ícone', 'condicao', 1, 1),
(UUID(), 'que utilizam o sistema poneyzap', 'condicao', 1, 1),
(UUID(), 'que utilizam o sistema poneyzap', 'condicao', 1, 1),
(UUID(), 'para recebimento de pedidos', 'condicao', 1, 1),
(UUID(), 'para recebimento de pedidos', 'condicao', 1, 1),
(UUID(), 'para envio de mensagens', 'condicao', 1, 1),
(UUID(), 'para envio de mensagens', 'condicao', 1, 1),
(UUID(), 'de chamada de vídeo', 'condicao', 1, 1),
(UUID(), 'de chamada de vídeo', 'condicao', 1, 1);

-- Total de palavras inseridas: 219